name: money_calculator
description: Мощный калькулятор расходов и доходов
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI и состояние
  provider: ^6.1.1
  flutter_slidable: ^3.0.1
  google_fonts: ^6.1.0
  
  # Работа с датами и форматирование
  intl: ^0.18.1
  
  # Хранение данных
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  
  # Графики и аналитика
  fl_chart: ^0.66.0
  
  # Уведомления
  flutter_local_notifications: ^19.0.0
  
  # Работа с камерой/галереей
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Если у вас есть ассеты, раскомментируйте:
  # assets:
  #   - assets/images/